# Maven
# Build your Java projects and run tests with Apache Maven.
# https://aka.ms/yaml

queue: 'Hosted Linux Preview'
steps:

- task: Maven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: 2ff763a7-ce83-4e1f-bc89-0ae63477cebe@1 #PublishBuildArtifacts@1
  inputs:
    artifactName: drop
    pathToPublish: '$(build.artifactStagingDirectory)'
    publishLocation: container
