# Gradle
# Build your Java projects and run tests with Gradle using a Gradle wrapper script.
# https://aka.ms/yaml

queue: 'Hosted VS2017'
steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: 2ff763a7-ce83-4e1f-bc89-0ae63477cebe@1 #PublishBuildArtifacts@1
  inputs:
    artifactName: drop
    pathToPublish: '$(build.artifactStagingDirectory)'
    publishLocation: container
